name: Binaries build

on:
  push:
    tags:
      - IGNORE-v*

jobs:
  build-windows:
    name: Build Windows binary (zip)
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Download R-Portable-Win
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://ta3info.com/R-Portable-Win.zip"
          target: runtime-files/
      - name: Package application
        run: npm run publish
        shell: pwsh
      - name: Upload Windows exe
        uses: actions/upload-artifact@v1
        with:
          name: exe
          path: ./out/make/zip/win32/x64/Subadult Dental Age Estimation-win32-x64-*.zip
